#include<bits/stdc++.h>
using namespace std;
#define xx              first
#define yy              second
#define pb              push_back;
#define mp              make_pair
#define LL              long long
#define PI              acos(-1.0)
#define AND(a,b)        ((a) & (b))
#define OR(a,b)         ((a)|(b))
#define XOR(a,b)        ((a) ^ (b))
#define f1(i,n)         for(int i=1;i<=n;i++)
#define f0(i,n)         for(int i=0;i<n;i++)
#define meminf(B)       memset(B,126,sizeof B)
#define DEG_to_REDI(X) (X*PI/180)
#define REDI_to_DEG(X) (180*X/(PI))

template <class T> inline T bigmod(T p,T e,T M){
    LL ret = 1;
    for(; e > 0; e >>= 1){
        if(e & 1) ret = (ret * p) % M;
        p = (p * p) % M;
    } return (T)ret;
}
template <class T> inline T gcd(T a,T b){if(b==0)return a;return gcd(b,a%b);}
template <class T> inline T modinverse(T a,T M){return bigmod(a,M-2,M);}

/*    ----------------------------------------
     |         Scratch where itches           |
      ----------------------------------------   */

int month[]={-1,31,28,31,30,31,30,31,31,30,31,30,31};  //Not Leap Year
int dx[]={1,0,-1,0};int dy[]={0,1,0,-1}; //4 Direction
//int dx[]={1,1,0,-1,-1,-1,0,1};int dy[]={0,1,1,1,0,-1,-1,-1};//8 direction
//int dx[]={2,1,-1,-2,-2,-1,1,2};int dy[]={1,2,2,1,-1,-2,-2,-1};//Knight Direction
//int dx[]={-1,-1,+0,+1,+1,+0};int dy[]={-1,+1,+2,+1,-1,-2}; //Hexagonal Direction
const double eps=1e-6;
const int MX=100005;
LL n,a[MX],cnt[MX];
LL mx,mn;
LL dp[MX];
LL DP(LL value)
{
    if(value>mx) return 0;
    LL &ptr=dp[value];
    if(ptr!=-1)return ptr;
    ptr=0;
    ptr=value*cnt[value]+DP(value+2);
    ptr=max(ptr,DP(value+1));
    return ptr;
}
int main()
{
  cin>>n;
  mx=-1;
  mn=(1<<31)-1;
  for(int i=0;i<n;i++)
  {
      cin>>a[i];
      cnt[a[i]]++;
      mx=max(mx,a[i]);
      mn=min(mn,a[i]);
  }
  memset(dp,-1,sizeof dp);
  // LONG LONG NA NILE WRONG ANSWER
  cout<<DP(mn)<<endl;






    return 0;
}

